### PR TITLE
Update Latex expressions

### PR DESCRIPTION
**Pull request by astro-ray**
Some changes might feel unnecessary, but I felt like it would be better to have those changes. Like the more conventional font for real number set or the extra line of explanation for linear transformation.

### CODE REVIEW

**Comment by dylannalex** [comment]
Hey @ritamsaha00, thanks for your PR. I've checked out your commit and here's a few notes:

1. I love that you added an extra explanation for linear transformations:

> A linear transformation is a mapping between two vector spaces $$f:\mathcal{V}\rightarrow\mathcal{W}$$ that preserves the operations of vector addition and scalar multiplication.
> If, $v_,v_2\in\mathcal{V}$, then: $$f(a_1v_1+a_2v_2)=a_1f(v_1)+a_2f(v_2)$$

I'd add that $a_1$ and $a_2$ are real values, the same way you said $v_,v_2\in\mathcal{V}$. I'd also include the $f$ after writing linear transformation on the first sentence. Here are the modifications:

A linear transformation $f$ is a mapping between two vector spaces $$f:\mathcal{V}\rightarrow\mathcal{W}$$ that preserves the operations of vector addition and scalar multiplication.
If, $v_,v_2\in\mathcal{V}$ and $a_1, a_2\in\mathbb{R}$, then: $$f(a_1v_1+a_2v_2)=a_1f(v_1)+a_2f(v_2)$$

2. On the README.md you replaced:

```
$$
\begin{bmatrix}
0 & -1\\
1 & 0
\end{bmatrix}
$$

$$
B = 
\begin{bmatrix}
1 & 1\\
0 & 1
\end{bmatrix}
$$
```

with:

```
$$
\begin{bmatrix}
0 & -1\\
1 & 0
\end{bmatrix} \text{and } B = 
\begin{bmatrix}
1 & 1\\
0 & 1
\end{bmatrix}
$$
```

I think what you did is cleaner, but you didn't add it on introduction.md. Is there any reason for that, or you just forgot to add it?

Overall, I really like your update on docs, great job! 
Please, fix those observations and I'd merge the PR. Also, feel free to improve anything else you consider necessary, just don't forget to do it in both README.md and introduction.md.

**Comment by astro-ray** [comment]
> but you didn't add it on introduction.md.

It's not that I didn't update the changes on introduction.md, the changes I made are already there. I changed README.md to match the introduction.md

```
{math}A = \begin{bmatrix}0 & -1\\1 & 0\end{bmatrix} and {math}B = \begin{bmatrix}1 & 1\\0 & 1\end{bmatrix}
```

> I'd add that $a_1$ and $a_2$ are real values

I avoided the term "real values" as mathematically $a_1$ and $a_2$ are an element of the field of the corresponding vector space. So, these are not necessarily real numbers ( though they are real in the context of this `curvipy` program). But I will add that $a_1$ and $a_2$ are scalars as I think the term scalar seems more appropriate.

**Comment by astro-ray** [comment]
**Another thing:** I have noticed that some popular authors/publishers use bold letters to differentiate vectors from other mathematical objects, so I will like to follow that convention.

**Comment by dylannalex** [comment]
Sure, go ahead!

**Comment by dylannalex** [comment]
Hey, @ritamsaha00. Few more things before merging your PR:

1. 

> It's not that I didn't update the changes on introduction.md, the changes I made are already there. I changed README.md to match the introduction.md
> `{math}'A = \begin{bmatrix}0 & -1\\1 & 0\end{bmatrix}' and {math}'B = \begin{bmatrix}1 & 1\\0 & 1\end{bmatrix}'`

To have the README.md and introduction.md consistent, that equation should be written as:
`{math}'A = \begin{bmatrix}0 & -1\\1 & 0\end{bmatrix} \text{and } B = \begin{bmatrix}1 & 1\\0 & 1\end{bmatrix}'`

**Note:** `{math}'expression'` (with `` instead of '') on introduction.md is equivalent to `$expression$` on README.md.

2. 

> Another thing: I have noticed that some popular authors/publishers use bold letters to differentiate vectors from other mathematical objects, so I will like to follow that convention.

After reviewing your document, I think it's better to write vectors as letter with an arrow on the top, like the $\vec{x}$ shown on **Tranformation Matrix** section:

> ### Transformation matrix
> 
> In linear algebra, linear transformations can be represented by matrices. If $T$ is a linear transformation mapping $\mathbb{R}^n$ to $\mathbb{R}^m$ and $\vec{x}$ is a column vector then

**Comment by astro-ray** [comment]
On that note, is there a reason why you put all the equations in inline mode in introduction.md?

**Comment by dylannalex** [comment]
Not at all, I'm new to making documentations. I've no problem if you consider that having the equations in inline mode is not the best practice and decide to change it!

Don't forget to fix the observations I made, specially the 2. 
> After reviewing your document, I think it's better to write vectors as letter with an arrow on the top, like the $\vec{x}$ shown on Tranformation Matrix section: ...

Once you update that, I will merge your PR!

**Comment by dylannalex** [comment]
Nice work @ritamsaha00, thank you for contributing to curvipy!

**Pull request merged**
